name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.20.0'
        id: go
        
      - uses: actions/checkout@v5

      - name: Test
        run: make test
